// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASEo8CMJ5xhQBbwyfSIBTfg0pKa-egN6s',
    appId: '1:635653256675:web:db4d9a25bfed0b6b0e5cd6',
    messagingSenderId: '635653256675',
    projectId: 'edubotnew',
    authDomain: 'edubotnew.firebaseapp.com',
    storageBucket: 'edubotnew.firebasestorage.app',
    measurementId: 'G-76Q93GPNF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAHQ39lGblX2xe4-zo8tzHsVJwf3OZi1w',
    appId: '1:635653256675:android:7c4af08c4ea3b2690e5cd6',
    messagingSenderId: '635653256675',
    projectId: 'edubotnew',
    storageBucket: 'edubotnew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGi1d-T7PbWM6GK8N_3XOxuRLxZnwMDFI',
    appId: '1:635653256675:ios:de347d74e017a4160e5cd6',
    messagingSenderId: '635653256675',
    projectId: 'edubotnew',
    storageBucket: 'edubotnew.firebasestorage.app',
    iosBundleId: 'com.example.edubotNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGi1d-T7PbWM6GK8N_3XOxuRLxZnwMDFI',
    appId: '1:635653256675:ios:de347d74e017a4160e5cd6',
    messagingSenderId: '635653256675',
    projectId: 'edubotnew',
    storageBucket: 'edubotnew.firebasestorage.app',
    iosBundleId: 'com.example.edubotNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASEo8CMJ5xhQBbwyfSIBTfg0pKa-egN6s',
    appId: '1:635653256675:web:5588d9f8fcec32cd0e5cd6',
    messagingSenderId: '635653256675',
    projectId: 'edubotnew',
    authDomain: 'edubotnew.firebaseapp.com',
    storageBucket: 'edubotnew.firebasestorage.app',
    measurementId: 'G-1WXNVN8E3P',
  );
}
